# Generated by Django 4.2.7 on 2023-11-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('close_price', models.FloatField()),
            ],
        ),
    ]
